target-version = "py312"
line-length=120

[lint]
select = [
    "F", # pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "I", # import sorting
    "D", # pydocstyle
]

ignore = [
    "D203", # conflict with D211
    "D213", # conflict with D212
    "D100",
    "D104"
]

[format]
quote-style = "double"
indent-style = "space"